---
 - name: Create directory
   file: 
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: 0755
   with_items:
    - { path: "{{ prometheus_path }}", owner: root, group: root }
    - { path: "{{ prometheus_volume_data }}", owner: nobody, group: root }
    - { path: "{{ prometheus_volume_config }}", owner: nobody, group: root }
    
 - name: Copy docker-compose.yml
   template:
     src: "{{ item.src }}"
     dest: "{{ item.dest }}"
   with_items:
     - { src: docker-compose.yml.j2, dest: "{{ prometheus_path }}/docker-compose.yml" }
     - { src: prometheus.yml.j2, dest: "{{ prometheus_volume_config }}/prometheus.yml" }

 - name: Docker-compose up container
   shell: docker-compose up -d
   args:
     chdir: "{{ prometheus_path }}"