---

   grafana_secutiry_admin_password:
   grafana_external_port: 3000
   grafana_address: "{{ groups['server'][0] }}:{{ grafana_external_port }}"
   grafana_path: /home/grafana
   grafana_volume_data: "{{ grafana_path }}/data"
   grafana_sys_user: grafana
   grafana_dashboard_uid: rYdddlPWk
   grafana_deploy: false
   grafana_create_datasource: false