---
 - name: Create directory
   file: 
    path: "{{ cadvisor_path }}"
    state: directory
    mode: 0755

 - name: Copy docker-compose.yml
   template:
     src: docker-compose.yml.j2
     dest: "{{ cadvisor_path }}/docker-compose.yml"

 - name: Docker-compose up container
   shell: docker-compose up -d
   args:
     chdir: "{{ cadvisor_path }}"