---
 - name: Configure server
   hosts: all
   remote_user: ubuntu
   become: yes
   become_user: root
   become_method: sudo
   roles:
     - { role: prometheus, when: prometheus_deploy }
     - { role: grafana, when: grafana_deploy }
     - { role: grafana_dashboard, when: grafana_create_datasource }
   