---
 - name: Add Grafana user
   user:
    name: "{{ grafana_sys_user }}"
    uid: 3000
    shell: /bin/false
    create_home: yes
    home: "{{ grafana_path }}"

 - name: Create directory
   file: 
    path: "{{ grafana_volume_data }}"
    state: directory
    owner: "{{ grafana_sys_user }}"
    group: "{{ grafana_sys_user }}"
    mode: 0750

 - name: Copy docker-compose.yml
   template:
     src: docker-compose.yml.j2
     dest: "{{ grafana_path }}/docker-compose.yml"

 - name: Docker-compose up container
   shell: docker-compose up -d
   args:
     chdir: "{{ grafana_path }}"

 - name: Wait Grafana Service wake up
   wait_for:
     host: "{{ groups['server'][0] }}"
     port: "{{ grafana_external_port }}"
     delay: 10
     state: drained