---
 - name: Add Grafana user
   user:
    name: "{{ grafana_sys_user }}"
    uid: 3000
    shell: /bin/false
    create_home: yes
    home: "{{ grafana_path }}"

 - name: Create directory
   file: 
    path: "{{ item }}"
    state: directory
    owner: "{{ grafana_sys_user }}"
    group: "{{ grafana_sys_user }}"
    mode: 0750
   with_items:
     - "{{ grafana_volume_data }}"

 - name: Copy docker-compose.yml
   template:
     src: docker-compose.yml.j2
     dest: "{{ grafana_path }}/docker-compose.yml"

 - name: Copy Json's dashboard
   copy:
     src: dashboard.json
     dest: "{{ grafana_path }}/dashboard.json"

 - name: Docker-compose up container
   shell: docker-compose up -d
   args:
     chdir: "{{ grafana_path }}"

 - name: Wait Grafana Service wake up
   wait_for:
     host: "{{ docker_host }}"
     port: "{{ grafana_external_port }}"
     delay: 10
     state: drained

 - name: Create Prometheus datasource
   grafana_datasource:
     name: "Prometheus"
     grafana_url: "http://{{ grafana_address }}"
     grafana_user: "admin"
     grafana_password: "{{ grafana_secutiry_admin_password }}"
     org_id: "1"
     ds_type: "prometheus"
     url: "{{ prometheus_url }}"
   when:
     - grafana_create_datasource

 - name: Create default Dashboard
   grafana_dashboard:
     grafana_url: "http://{{ grafana_address }}"
     grafana_user: "admin"
     grafana_password: "{{ grafana_secutiry_admin_password }}"
     state: present
     uid: "{{ grafana_dashboard_uid }}"
     overwrite: yes
     path: "{{ grafana_path }}/dashboard.json"
   when:
     - grafana_create_datasource