---

 - name: Download Node_Exporter
   get_url:
     url: "{{ node_exporter_url }}"
     dest: "{{ node_exporter_download_path }}"
     mode: '0750'
    
 - name: Unzip tar file {{ node_exporter_name }}.tar.gz
   unarchive:
     remote_src: yes
     src: "{{ node_exporter_download_path }}/{{ node_exporter_name }}.tar.gz"
     dest: "{{ node_exporter_download_path }}"

 - name: Copy {{ node_exporter_name }} to {{ node_exporter_download_path }}
   copy:
     remote_src: yes
     src: "{{ node_exporter_download_path }}/{{ node_exporter_name }}/node_exporter"
     dest: "{{ node_exporter_path }}"
     mode: '0750'
    
 - name: Copy Systemd Service
   copy:
     src: node_exporter.service
     dest: /etc/systemd/system/

 - name: Configure systemd service
   systemd:
     name: node_exporter
     enabled: yes
     daemon_reload: yes
     state: started

 - name: Remove temp file {{ node_exporter_name }}.tar.gz
   file:
     path: "/tmp/{{ node_exporter_name }}.tar.gz"
     state: absent